fix infra outputs when restoring from snapshots
useparagon/aws-on-prem pull request #29
Opened 2024-03-15 20:40 UTC by ishmaelthedestroyer

### Overview

This PR fixes the outputs in the infra workspace when restoring the RDS database from a snapshot (`RDS_RESTORE_FROM_SNAPSHOT=true`). Null values aren't allowed in string interpolations.

This use case is primarily used when spinning up + down ephemeral environments when load testing.

### Unrelated Changes

- disable bucket versioning when `DISABLE_DELETION_PROTECTION=true`, which makes it harder + take longer to delete buckets
- only allow lowercase characters when generating Grafana and PGAdmin emails

2024-03-15 21:10 UTC, jromero-pg requested changes

2024-03-15 21:10 UTC, jromero-pg commented on terraform/workspaces/paragon/monitors/pgadmin.tf
> +  upper       = false
This is updating the password instead of the email address (prefix).

2024-03-18 13:26 UTC, tedparagon approved these changes
Looks good pending the fix that @jromero-pg requested.

2024-03-19 19:06 UTC, jromero-pg approved these changes

2024-03-21 21:09 UTC, merged